pipeline {
    agent any
    environment {
        APPLICATION_PORT = '8080'
        DB_URL = credentials('DB_URL')
        DB_USER = credentials('DB_USER')
        DB_PASSWORD = credentials('DB_PASSWORD')
        AWS_ACCESS_KEY = credentials('AWS_ACCESS_KEY')
        AWS_SECRET_KEY = credentials('AWS_SECRET_KEY')
        AWS_BUCKET = 'manga-rider-bucket-1'
        AWS_REGION = 'eu-central-1'
    }
    stages {
        stage('Build') {
            steps {
                git branch: 'main', url: 'https://github.com/Manga-Rider/backend.git'
                sh '''
                    export JAVA_HOME="/lib/jvm/jdk-21-oracle-x64"
                    
                    export APPLICATION_PORT="${APPLICATION_PORT}"
                    export DB_URL="${DB_URL}"
                    export DB_USER="${DB_USER}"
                    export DB_PASSWORD="${DB_PASSWORD}"
                    export AWS_ACCESS_KEY="${AWS_ACCESS_KEY}"
                    export AWS_SECRET_KEY="${AWS_SECRET_KEY}"
                    export AWS_BUCKET="${AWS_BUCKET}"
                    export AWS_REGION="${AWS_REGION}"
                    
                    chmod 744 ./mvnw
                    rm -f .env
                    echo "SPRING_PROFILES_ACTIVE=prod" >> .env
                    ./mvnw clean package
                    cp ./target/demo*.jar ../../backend.jar
                '''
            }
        }
        stage('Deploy') {
            steps {
                sh '''
                    sudo systemctl stop manga-rider-backend || true
                    sudo systemctl enable manga-rider-backend --now
                '''
            }
        }
    }
}